Ajax/Ajax/Models/Country.cs
using System.Collections.Generic;
using System.Linq;

namespace Ajax.Models
{
    public class Country
    {
        public int Id { get; set; }

        public int ContinentId { get; set; }

        public string Name { get; set; }        
    }

    public class GeoServices
    {
        static List<Country> _countries = new List<Country>()
        {
            new Country() {ContinentId = 1, Id = 1, Name = "France"},
            new Country() {ContinentId = 1, Id = 2, Name = "Spain"},
            new Country() {ContinentId = 1, Id = 3, Name = "Portugal"},
            new Country() {ContinentId = 1, Id = 4, Name = "Italy"},
            new Country() {ContinentId = 1, Id = 5, Name = "Denmark"},
            new Country() {ContinentId = 1, Id = 6, Name = "Greece"},
            new Country() {ContinentId = 2, Id = 7, Name = "China"},
            new Country() {ContinentId = 2, Id = 8, Name = "India"},
            new Country() {ContinentId = 2, Id = 9, Name = "Japan"},
            new Country() {ContinentId = 2, Id = 10, Name = "Korea"},
            new Country() {ContinentId = 2, Id = 11, Name = "Taiwan"},
            new Country() {ContinentId = 3, Id = 12, Name = "United States"},
            new Country() {ContinentId = 3, Id = 13, Name = "Brazil"},
            new Country() {ContinentId = 3, Id = 14, Name = "Mexico"},
            new Country() {ContinentId = 3, Id = 15, Name = "Colombia"},
            new Country() {ContinentId = 3, Id = 16, Name = "Argentina"},
        };

        public IEnumerable<Country> GetCountriesByContinent(int continentId)
        {
            return _countries.Where(c => c.ContinentId == continentId);
        }
    }
}

Ajax/Ajax/ViewModels/FriendViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Ajax.ViewModels
{
    public class FriendViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string LastName { get; set; }
        [EmailAddress]
        public string Email { get; set; }
    }
}

Ajax/Ajax/Controllers/FriendsController.cs
using Ajax.ViewModels;
using System.Web.Mvc;

namespace Ajax.Controllers
{
    public class FriendsController : Controller
    {
        [HttpPost]
        public ActionResult SaveData(FriendViewModel vm)
        {
            return Json(ModelState.IsValid);
        }
    }
}

Ajax/Ajax/Controllers/GeoController.cs
using Ajax.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using static Ajax.Models.Country;

namespace Ajax.Controllers
{
    public class GeoController : Controller
    {
        //
        // GET: /Geo/GetCountries
        [HttpPost]
        public ActionResult GetCountries(int regionId)
        {
            IEnumerable<Country> countries =
                   new GeoServices().GetCountriesByContinent(regionId);
            return Json(countries);
        }
    }
}

Ajax/Ajax/Controllers/HomeController.cs
using Ajax.ViewModels;
using System.Web.Mvc;

namespace Ajax.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPartialView(string name)
        {
            return PartialView("_Greetings", name);
        }

        [HttpPost]
        public ActionResult SaveData(FriendViewModel vm)
        {
            return Json(ModelState.IsValid);
        }
    }
}

Ajax/Ajax/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Ajax";
}

<div class="row">
    <div class="col-xs-4">
        <h3>Partial views</h3>
        <div class="form-group">
            <label for="name1" class="control-label">Name:</label>
            <input id="name1" type="text" class="form-control input-sm" />
        </div>
        <div class="form-group">
            <button id="send1" class="btn btn-primary">Send</button>
        </div>
        <div id="result1"></div>
    </div>
    <div class="col-xs-4">
        <h3>Ajax simple data</h3>
        <div class="form-group">
            <label for="name2" class="control-label">Name:</label>
            <input id="name2" type="text" class="form-control input-sm" />
        </div>
        <div class="form-group">
            <label for="lastname2" class="control-label">Last name:</label>
            <input id="lastname2" type="text" class="form-control input-sm" />
        </div>
        <div class="form-group">
            <label for="email2" class="control-label">Email:</label>
            <input id="email2" type="text" class="form-control input-sm" />
        </div>
        <div class="form-group">
            <button id="send2" class="btn btn-primary">Send</button>
        </div>
        <div id="result2" class="alert" style="display: none"></div>
    </div>
    <div class="col-xs-4">
        <h3>Ajax dropdowns</h3>
        <div class="form-group">
            <label for="ddContinent" class="control-label">Continent</label>
            <select id="ddContinent" class="form-control">
                <option value="">(Select continent)</option>
                <option value="1">Europe</option>
                <option value="2">Asia</option>
                <option value="3">America</option>
            </select>
        </div>
        <div class="form-group">
            <label for="ddCountry" class="control-label">Country</label>
            <select id="ddCountry" class="form-control">
                <option value="">(Select country)</option>
            </select>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $("#send1").click(getPartial);
            $("#send2").click(saveData);
            $("#ddContinent").change(reloadCountries);
        });

        // Partial view
        function getPartial() {
            $("#result1").hide();
            $.ajax({
                url: "@Url.Action("GetPartialView", "Home")",
                data: { name: $("#name1").val() },
                type: "post",
                success: function (data) {
                    $("#result1").html(data).slideDown("fast");
                    setTimeout(function () { $("#result1").slideUp("fast"); }, 2000);
                },
                error: function () {
                    alert("Oooops! It seems there is a problem...");
                }
            });
        }

        // Ajax simple data
        function saveData() {
            $("#result2").hide();
            $.ajax({
                url: "@Url.Action("SaveData", "Friends")",
                data: {
                name: $("#name2").val(),
                lastname: $("#lastname2").val(),
                email: $("#email2").val(),
                },
                type: "post",
                success: function (returnData) {
                    var $result = $("#result2");
                    $result.removeClass("alert-info").removeClass("alert-danger");
                    var text = returnData ? "Data successfully stored" : "Error storing data!!";
                    var cssClass = returnData ? "alert-info" : "alert-danger";
                    $("#result2").addClass(cssClass).text(text).slideDown("fast");
                },
                error: function () {
                    alert("Error in Ajax call");
                }
            });
        }

        // Ajax dropdowns
        function reloadCountries() {
            $.ajax({
                url: "@Url.Action("GetCountries", "Geo")",
                data: { regionId: $("#ddContinent").val() },
                type: "post",
                success: function (data) {
                    var dd = $("#ddCountry")[0];
                    dd.options.length = 0;
                    for (var i = 0; i < data.length; i++) {
                        var country = data[i];
                        dd.options[i] = new Option(country.Name, country.Id);
                    }
                },
                error: function (request, status, error) {
                    alert("Error in Ajax call");
                }
            });
        }
    </script>
}

Ajax/Ajax/Views/Home/_Greetings.cshtml
@model string

<div class="alert alert-info">
    Hi, @Model!
    Current time: @DateTime.Now.ToLongTimeString()
</div>

Ajax/Ajax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />        
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />        
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Ajax", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav"></ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>
        
        @RenderSection("Scripts", false)
    </body>
</html>